
name: Rspec Test

on:
  push:
    branches:
    - master

jobs:
  rspec-test:
    # コンテナはLinuxベースのオペレｰ手イングシステム内で実行する
    runs-on: ubuntu-latest
    # `container-job`が実行されるDocker Hubイメージ
    container:
      image: ruby:alpine
      env:
        RAILS_ENV: test


    services:
      mysql:
        image: mysql:5
        env:
          MYSQL_ROOT_PASSWORD: password

    steps:
      - uses: actions/checkout@v2

      - name: bundle install
        run: bundle

      - name: rails db:create
        run: rails db:create
      
      - name: rails db:migrate
        run: rails db:migrate



# # on: [push]

# # jobs:
# #   test:
# #     name: test
# #     runs-on: ubuntu-latest
# #     steps:
# #     - uses: actions/checkout@master

# #     - name: run test
# #       uses: cedrickring/golang-action/go1.13@1.4.1
# #       env:
# #         GO111MODULE: "on"
# #         PROJECT_PATH: "./src"
# #       with:
# #         args: |
# #           go test -coverprofile=cover.out ./...
# #           ls

# #     - uses: codecov/codecov-action@v1
# #       with:
# #         token: ${{ secrets.CODECOV_TOKEN }}
# #         file: ./cover.out